### ISSUE TITLE
Compatibility with hibernate 4.2.x

### ISSUE THREAD

**Issue by saugion** [skuzniarz/hibernate-envers-ext#1]
Hello,
i'm using hibernate 4.2.21.FINAL and i can't upgrade it right now.
Do you think it'd be possible to extend your work also to this version?
Thanks in advance

**Comment by szczepankuzniarz** [comment]
There is already a 4.2.x branch: https://github.com/skuzniarz/hibernate-envers-ext/tree/4.2.x, I've just upgraded it to 4.2.21.Final: https://github.com/skuzniarz/hibernate-envers-ext/releases/tag/4.2.21.Final. Enjoy :-)

**Comment by saugion** [comment]
Thanks, it works perfectly!
